src/java/Controllers/MembersController.java
package Controllers;

import DbEntities.Members;
import Controllers.util.JsfUtil;
import Controllers.util.PaginationHelper;
import Beans.MembersFacade;
import DbEntities.Payments;
import DbEntities.Reservations;
import DbEntities.SummerHouses;
import com.google.gson.Gson;
import java.io.IOException;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import static org.apache.openjpa.persistence.jest.ObjectFormatter.dateFormat;
import org.primefaces.context.RequestContext;

@Named("membersController")
@SessionScoped
public class MembersController implements Serializable {

    private Integer additionalPoints;
    private Members current;
    private Members selectedMember;
    private DataModel items = null;
    @EJB
    private Beans.MembersFacade ejbFacade;
    @EJB
    private Beans.ReservationsFacade reservationsFacade;
    @EJB
    private Beans.PaymentsFacade paymentsFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public MembersController() {
    }

    public Integer getAdditionalPoints() {
        return additionalPoints;
    }
    
    public void setAdditionalPoints(Integer points) {
        additionalPoints = points;
    }
    
    public Members getSelectedMember() {

        return selectedMember;
    }
    
    public Members getSelected() {
        if (current == null) {
            current = new Members();
            selectedItemIndex = -1;
        }
        return current;
    }

    private MembersFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "/members/List";
    }

    public String prepareListAdmin() {
        recreateModel();
        return "/members/ListAdmin";
    }

    public String prepareView() {
        current = (Members) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/members/View";
    }

    public String prepareCreate() {
        current = new Members();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Resources").getString("MembersCreated"));
            recreateModel();
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Resources").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Members) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "/members/Edit";
    }

    public String prepareEditAdmin(Members member) {
        selectedMember = member;
        return "/members/EditAdmin";
    }

    public String updateAdmin() {
        try {
            Integer currentPoints = 0;
            if(selectedMember.getPoints() != null){
                currentPoints = selectedMember.getPoints();
            }
            currentPoints = currentPoints + additionalPoints;
            if(currentPoints > 99999){
                JsfUtil.addErrorMessage("Taškų skaičius viršija maksimalų taškų skaičių 99999");
            return null;
            }
            selectedMember.setPoints(currentPoints);
            if(Objects.equals(selectedMember.getId(), current.getId())){
                current.setPoints(currentPoints);
            }
            additionalPoints = null;
            getFacade().edit(selectedMember);
            //JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Resources").getString("MembersUpdated"));
            return "/members/ListAdmin";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Resources").getString("PersistenceErrorOccured"));
            return null;
        }
    }
    
    public String update() {
        try {
            getFacade().edit(current);
            //JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Resources").getString("MembersUpdated"));
            return "/members/ListAdmin";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Resources").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String updateProfile() {
        System.out.println("vyksta");
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Resources").getString("MembersUpdated"));
            return "/profile/profile";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Resources").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroyMember(Members member) {
        try {
            getFacade().remove(member);
            current = null;
            JsfUtil.addSuccessMessage("Sekmingai išsiregistruota");
            return "/members/MemberDestroyed";
        } catch (Exception e) {
            JsfUtil.addErrorMessage("Nepavyko išsiregistruoti");
        }
        return null;
    }
    
    public String destroy() {
        current = (Members) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "/members/List";
    }

    public String destroyAdmin(Members member) {
       try {
           if(member == current){
               current = null;
           }
            getFacade().remove(member);
            recreateModel();
            JsfUtil.addSuccessMessage("Sekmingai išsiregistruota");
        } catch (Exception e) {
            JsfUtil.addErrorMessage("Nepavyko išsiregistruoti");
        }
        return "/members/ListAdmin";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "/members/View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "/members/List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Resources").getString("MembersDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Resources").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "/members/List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "/members/List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Members getMembers(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    public ArrayList<Members> filterCandidates() {
        ArrayList<Members> members = (ArrayList<Members>) ejbFacade.findAll();
        ArrayList<Members> result = new ArrayList<Members>();
        for (int i = 0; i < members.size(); i++) {
            if (members.get(i).getType() == 2) {
                result.add(members.get(i));
            }
        }
        return result;
    }

    public ArrayList<Members> filterMembers() {
        ArrayList<Members> members = (ArrayList<Members>) ejbFacade.findAll();
        ArrayList<Members> result = new ArrayList<Members>();
        for (int i = 0; i < members.size(); i++) {
            if (members.get(i).getType() != 2) {
                result.add(members.get(i));

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        #{membersController.getMemberLoginStatus(3)}
        Hello from Facelets
        <br />
        <h:link outcome="/additionalServices/List" value="Show All AdditionalServices Items"/>
        <br />
        <h:link outcome="/members/List" value="Show All Members Items"/>
        <br />
        <h:link outcome="/payments/List" value="Show All Payments Items"/>
        <br />
        <h:link outcome="/reservations/List" value="Show All Reservations Items"/>
        <br />
        <h:link outcome="/summerHouses/List" value="Show All SummerHouses Items"/>

        <br/>
        <h:form id="email_form">
            <br/>
            <br/>
            <h:outputText value="Email tests:"/>
            <br/>
            <h:inputText id="emailField" binding="#{emailBinding}" required="true" requiredMessage="Email field is required"/> 
            <br/>
            <h:commandButton value="Invitation Email test" action="#{emailGenerator.sendEmail(emailBinding.value, 0)}"/>
            <br/>
            <h:commandButton value="Confirmation Email test" action="#{emailGenerator.sendEmail(emailBinding.value, 1)}"/>
        </h:form>
        <br/>
        <h:form id="reservations_form">
            <h:outputLabel value="#{resources.CreateReservationsLabel_membersId}" for="membersId" />
            <h:selectOneMenu id="membersId" value="#{reservationsController.selectedMember}" title="#{resources.CreateReservationsTitle_membersId}" >
                <f:selectItems value="#{membersController.itemsAvailableSelectOne}"/>
            </h:selectOneMenu>
            <h:commandButton value="Reservations" action="/reservations"/>
        </h:form>
        <br/>
        <h:link outcome="/homePage/home" value="Home Page"/>
        <br/>

        <h:form id="FB_TEST">
            <h:commandButton value="FB login test" action="/index_1"/>
        </h:form>
        <br/>
        <br />
        <h:link outcome="/configurations/List" value="Show All Configurations Items"/>
    </h:body>

</html>

web/members.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Nariai</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        #{membersController.getMemberLoginStatus(2)}
        <h1>Nariai</h1>
        <h:form>
            <h:commandButton value="Patikrinti, kurie nariai atostogaus pasirinktu laikotarpiu" action="memberFilter/membersByDate" style="height:30px;width:350px;text-align:center"/>
        </h:form>
        <h:form id="membersForm" styleClass="jsfcrud_list_form">    
            <h:outputText escape="false" value="#{resources.ListMembersEmpty}" rendered="#{membersController.items.rowCount == 0}"/>
            <h:panelGroup rendered="#{membersController.filterMembers().size() > 0}">
                <h:outputText value="#{membersController.pagination.pageFirstItem + 1}..#{membersController.pagination.pageLastItem + 1}/#{membersController.pagination.itemsCount}"/>
                <h:commandLink action="#{membersController.previous}" value="#{resources.Previous} #{membersController.pagination.pageSize}" rendered="#{membersController.pagination.hasPreviousPage}"/>
                <h:commandLink action="#{membersController.next}" value="#{resources.Next} #{membersController.pagination.pageSize}" rendered="#{membersController.pagination.hasNextPage}"/>
                <h:dataTable value="#{membersController.filterMembers()}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" columnClasses="customWidth,customWidth,customWidth,customWidth" rules="all" style="border:solid 1px">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Vardas"/>
                        </f:facet>
                        <h:outputText value="#{item.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Pavardė"/>
                        </f:facet>
                        <h:outputText value="#{item.surname}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="El. Paštas"/>
                        </f:facet>
                        <h:outputText value="#{item.email}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value=""/>
                        </f:facet>
                        <h:commandButton value="Peržiūrėti profilį" action="/profile/profileOther" actionListener="#{membersController.setProfileMemberId(item.id)}" style="width: 200px"/>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
            <br/>
            <h:commandButton value="Pagrindinis puslapis" action="/homePage/home" style="height: 30px;width:350px"/>
        </h:form>
    </h:body>
</html>

web/oneHouse.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Rezervacija</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        <h:outputText value="#{summerHousesController.htmlText}" escape="false"/>
        <br/>
        <br/>
        #{membersController.getMemberLoginStatus(2)}
        <!-- Is karto nusettinu summerHousesID i pasirinkta nama. Cia irgi reiketu paimt members ID pagal prisijungusi nari. Kolkas palieku select boxa-->
        #{reservationsController.selected.setSummerHousesId(summerHousesController.selectedHouse)}  
        #{reservationsController.selected.setMembersId(membersController.currentMember)}
        <h:panelGroup id="messagePanel" layout="block">
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
        </h:panelGroup>
        <h:form id="ms" onsubmit="return validateForm()">
            <h:panelGrid columns="2">
                <h:outputLabel value="Rezervuoti pradžios data:" for="reservationFromDate" />
                <h:inputText id="reservationFromDate" value="#{reservationsController.selected.reservationFromDate}" title="#{resources.CreateReservationsTitle_reservationFromDate}" required="true" requiredMessage="Įveskite pradžios datą." style="width: 200px">
                    <f:convertDateTime pattern="yyyy-MM-dd" />
                    <f:validator validatorId="mondayValidator"/>
                </h:inputText>
                <h:outputLabel value="Rezervuoti pabaigos data:" for="reservationToDate" />
                <h:inputText id="reservationToDate" value="#{reservationsController.selected.reservationToDate}" title="#{resources.CreateReservationsTitle_reservationToDate}" required="true" requiredMessage="Įveskite pabaigos datą." style="width: 200px">
                    <f:convertDateTime pattern="yyyy-MM-dd" />
                    <f:validator validatorId="sundayValidator"/>
                </h:inputText>
                <h:outputLabel value="Papildoma paslauga:" for="additionalServicesId" />
                <h:selectOneMenu id="additionalServicesId" value="#{reservationsController.selected.additionalServicesId}" title="#{resources.CreateReservationsTitle_additionalServicesId}" style="width: 200px">
                    <f:selectItems value="#{additionalServicesController.itemsAvailableSelectOne}"/>
                </h:selectOneMenu>
            </h:panelGrid>
            <h:commandButton value="Rezervuoti" action="#{reservationsController.customCreate(summerHousesController.selectedHouse, reservationsController.selected.reservationFromDate, reservationsController.selected.reservationToDate)}" style="height: 30px;width: 360px"/>
        </h:form>
        <br/>
        <h:form>
            <h:commandButton value="Pagrindinis puslapis" action="/homePage/home" style="height: 30px;width:360px"/>
        </h:form>
    </h:body>
</html>

web/reservations.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Vasarnamiai</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        #{membersController.getMemberLoginStatus(2)}
        <center>
            <br/>
            <h:form styleClass="jsfcrud_list_form">
            <h:panelGroup rendered="#{reservationsController.items.rowCount > 0}">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                <h:dataTable value="#{reservationsController.listReservations(reservationsController.selectedMember)}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" >
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{resources.ListReservationsTitle_reservationFromDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.reservationFromDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{resources.ListReservationsTitle_reservationToDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.reservationToDate}">
                                <f:convertDateTime pattern="yyyy-MM-dd" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{resources.ListReservationsTitle_additionalServicesId}"/>
                            </f:facet>
                            <h:outputText value="#{item.additionalServicesId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{resources.ListReservationsTitle_membersId}"/>
                            </f:facet>
                            <h:outputText value="#{item.membersId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value=""/>
                            </f:facet>
                            <h:commandButton value="Užmokėti" action="#{paymentsController.payForReservation(item)}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
        </h:form>
        </center>
    </h:body>
</html>

web/summerHouses.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Vasarnamiai</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        #{membersController.getMemberLoginStatus(2)}
        <h1>Vasarnamiai</h1>
        <br/>
        <h:form id="summerHouses_form">
            <h:panelGrid columns="4">
                <h:commandButton value="Paieška pagal pavadinimą" action="filteredSummerHouses/byName" style="height:30px;width:267px;text-align:center"/>
                <h:commandButton value="Paieška pagal vietų skaičių" action="filteredSummerHouses/byMaxGuests" style="height:30px;width:267px;text-align:center"/>
                <h:commandButton value="Paieška pagal kainą" action="filteredSummerHouses/byPrice" style="height:30px;width:267px;text-align:center"/>
                <h:commandButton value="Paieška pagal galimą rezervacijos datą" action="filteredSummerHouses/byAvailability" style="height:30px;width:267px;text-align:center"/>
            </h:panelGrid>
        </h:form>
        <h:form styleClass="jsfcrud_list_form">
            <br/>
            <h:panelGroup rendered="#{summerHousesController.items.rowCount > 0}">
                <h:outputText value="#{summerHousesController.pagination.pageFirstItem + 1}..#{summerHousesController.pagination.pageLastItem + 1}/#{summerHousesController.pagination.itemsCount}"/>
                <h:commandLink action="#{summerHousesController.previous}" value="#{resources.Previous} #{summerHousesController.pagination.pageSize}" rendered="#{summerHousesController.pagination.hasPreviousPage}"/>
                <h:commandLink action="#{summerHousesController.next}" value="#{resources.Next} #{summerHousesController.pagination.pageSize}" rendered="#{summerHousesController.pagination.hasNextPage}"/>
                <br/>
                <h:dataTable value="#{summerHousesController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" columnClasses="customWidth2, customWidth2, customWidth2, customWidth2, customWidth2, customWidth2, customWidth2" rules="all" style="border:solid 1px" >
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Pavadinimas"/>
                        </f:facet>
                        <h:outputText value="#{item.name}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Numeris"/>
                        </f:facet>
                        <h:outputText value="#{item.number}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Vietų skaičius"/>
                        </f:facet>
                        <h:outputText value="#{item.maxGuests}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Naudojamas nuo"/>
                        </f:facet>
                        <h:outputText value="#{item.availableFrom}">
                            <f:convertDateTime pattern="yyyy-MM-dd" />
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Naudojamas iki"/>
                        </f:facet>
                        <h:outputText value="#{item.availableTo}">
                            <f:convertDateTime pattern="yyyy-MM-dd" />
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Kaina"/>
                        </f:facet>
                        <h:outputText value="#{item.price}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value=""/>
                       </f:facet>
                        <h:commandButton value="Rezervuoti" action="/oneHouse" actionListener="#{summerHousesController.toHtml(item.id)}" style="width:150px"/>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
            <br/>
            <h:commandButton value="Pagrindinis puslapis" action="/homePage/home" style="height: 30px;width:267px"/>
        </h:form>
    </h:body>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        #{membersController.getMemberLoginStatus(3)}
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>